'use strict';
const { v4: uuidv4 } = require('uuid');

module.exports = {
    up: async (queryInterface, Sequelize) => {
        /**
         * Add seed commands here.
         *
         * Example:
         * await queryInterface.bulkInsert('People', [{
         *   name: 'John Doe',
         *   isBetaMember: false
         * }], {});
         */
        await queryInterface.bulkInsert('workoutPrograms', [
            {
                id: uuidv4(),
                workoutProgramTitle: `Jim Wendler's 5/3/1`,
                workoutProgramDesc: `Jim Wendler’s 5/3/1 is all about starting with very light weights while progressing slowly and consistently. This extremely popular strength training program is based off of the rep schemes 5, 3, 1, as the name suggests. Throughout the routine you will work with percentages based off of your max, and strive to hit rep PR’s each workout.`,
                equipment: `gym Required`,
                difficulty: `intermediate`,
                workoutSchedule: `3-4 Days/Week`,
                workoutLength: `1-2 Hours`,
                rating: 4.5,
                createdAt: new Date(),
                updatedAt: new Date(),
                CategoryId: `10dc1790-c24d-4421-8aa9-9acd0148be8c`,
                category: `powerlifting`,
                reviews: 15,
            },
            {
                id: uuidv4(),
                workoutProgramTitle: `StrongLifts 5x5`,
                workoutProgramDesc: `StrongLifts 5x5 includes two workouts composed of five different movements. These movements include the squat, deadlift, overhead press, bench press, and barbell row. The rep scheme is consistent, along with the loading scheme per each workout. This workout routine is designed to progress an athlete slow through a simple linear periodized program, aka long-term one direction steady progress. For true beginners, it’s recommended starting very light (even using the bar) and for the barbell novice a starting weight of 50% of your 5-RM is recommended.`,
                equipment: `gym Required`,
                difficulty: `beginner`,
                workoutSchedule: `3-4 Days/Week`,
                workoutLength: `1-2 Hours`,
                rating: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                CategoryId: `10dc1790-c24d-4421-8aa9-9acd0148be8c`,
                category: `powerlifting`,
                reviews: 21,
            },
            {
                id: uuidv4(),
                workoutProgramTitle: `Chinese Olympic Weightlifting Program`,
                workoutProgramDesc: `This program is a 4 week peaking block designed for competition preparation. Originally designed for school-aged lifters.`,
                equipment: `gym Required`,
                difficulty: `intermediate`,
                workoutSchedule: `3-4 Days/Week`,
                workoutLength: `1-2 Hours`,
                rating: 2.5,
                createdAt: new Date(),
                updatedAt: new Date(),
                CategoryId: `5417c5da-7ea6-4fd5-a8ea-6df31fda055b`,
                category: `weightlifting`,
                reviews: 52,
            },
            {
                id: uuidv4(),
                workoutProgramTitle: `Murph CrossFit Program`,
                workoutProgramDesc: `Named after the late Navy Lieutenant Michael Murphy, who was killed in Afghanistan in 2005, it was supposedly his favorite.There are many ways to scale: partitioning, substituting exercises, and adding partners. But just like original Coke, there’s nothing like the real thing.`,
                equipment: `gym Required`,
                difficulty: `advanced`,
                workoutSchedule: `3-4 Days/Week`,
                workoutLength: `1-2 Hours`,
                rating: 3,
                createdAt: new Date(),
                updatedAt: new Date(),
                CategoryId: `a2d1e6b9-cb28-4505-bd96-935b31675f27`,
                category: `crossfit`,
                reviews: 12,
            },
            {
                id: uuidv4(),
                workoutProgramTitle: `German Volume Training`,
                workoutProgramDesc: `This bodybuilding program is a short-term way to exhaust yourself and gain some muscle mass and strength.`,
                equipment: `gym Required`,
                difficulty: `advanced`,
                workoutSchedule: `3-4 Days/Week`,
                workoutLength: `1-2 Hours`,
                rating: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                CategoryId: `8f0500ee-302b-4f64-b2da-3c1f35100fc9`,
                category: `bodybuilding`,
                reviews: 5,
            },
            {
                id: uuidv4(),
                workoutProgramTitle: `nSuns 5/3/1`,
                workoutProgramDesc: `nSuns 5/3/1 is a linear progression powerlifting program that was inspired by Jim Wendler’s 5/3/1 strength program. It progresses on a weekly basis, making it well suited for late stage novice and early intermediate lifters. It is known for its challenging amount of volume.`,
                equipment: `gym Required`,
                difficulty: `any`,
                workoutSchedule: `3-4 Days/Week`,
                workoutLength: `1-2 Hours`,
                rating: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                CategoryId: `10dc1790-c24d-4421-8aa9-9acd0148be8c`,
                category: `powerlifting`,
                reviews: 65,
            },
            {
                id: uuidv4(),
                workoutProgramTitle: `GZCL Methods`,
                workoutProgramDesc: `As GZCL is more of a framework than a strict program, there are many ways to adapt GZCL principles to existing training and find a version that fits your needs. `,
                equipment: `gym Required`,
                difficulty: `any`,
                workoutSchedule: `3-4 Days/Week`,
                workoutLength: `1-2 Hours`,
                rating: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                CategoryId: `10dc1790-c24d-4421-8aa9-9acd0148be8c`,
                category: `powerlifting`,
                reviews: 2,
            },
            {
                id: uuidv4(),
                workoutProgramTitle: `Daily Undulating Periodization (DUP)`,
                workoutProgramDesc: `After linear strength gains have been exhausted on training programs like Starting Strength, Strong Lifts, Candito Linear Program, or GZCL Linear Progression, DUP is a sound training method that allows for steady progress without over-fatiguing the athlete. This is why it is also referred to as non-linear periodization.`,
                equipment: `gym Required`,
                difficulty: `any`,
                workoutSchedule: `3-4 Days/Week`,
                workoutLength: `1-2 Hours`,
                rating: 5,
                createdAt: new Date(),
                updatedAt: new Date(),
                CategoryId: `10dc1790-c24d-4421-8aa9-9acd0148be8c`,
                category: `powerlifting`,
                reviews: 23,
            },
            {
                id: uuidv4(),
                workoutProgramTitle: `Starting Strength`,
                workoutProgramDesc: `One of the most popular novice lifting programs, Starting Strength is a textbook (literally) strength program for beginner lifters to rapidly develop proficiency with basic compound movements and get stronger.`,
                equipment: `gym Required`,
                difficulty: `beginner`,
                workoutSchedule: `3-4 Days/Week`,
                workoutLength: `1-2 Hours`,
                rating: 5,
                createdAt: new Date(),
                updatedAt: new Date(),
                CategoryId: `10dc1790-c24d-4421-8aa9-9acd0148be8c`,
                category: `powerlifting`,
                reviews: 32,
            },
            {
                id: uuidv4(),
                workoutProgramTitle: `Sheiko Programs`,
                workoutProgramDesc: `Sheiko programs are powerlifting programs attributed to Boris Sheiko, renowned Russian powerlifting coach. His programs are known for their high volume and great results for those who can complete them.More of a loose working template than a strict program, many different variations of Sheiko powerlifting programs have been circulating Internet forums for years.`,
                equipment: `gym Required`,
                difficulty: `any`,
                workoutSchedule: `any`,
                workoutLength: `any`,
                rating: 5,
                createdAt: new Date(),
                updatedAt: new Date(),
                CategoryId: `10dc1790-c24d-4421-8aa9-9acd0148be8c`,
                category: `powerlifting`,
                reviews: 3,
            },
            {
                id: uuidv4(),
                workoutProgramTitle: `Juggernaut Training Method`,
                workoutProgramDesc: `Based upon Juggernaut Training Systems and Chad Wesley Smith, the Juggernaut Method incorporates significant amounts of submaximal work to build work capacity in the lifter without overly taxing the CNS.`,
                equipment: `gym Required`,
                difficulty: `intermediate`,
                workoutSchedule: `any`,
                workoutLength: `any`,
                rating: 3,
                createdAt: new Date(),
                updatedAt: new Date(),
                CategoryId: `10dc1790-c24d-4421-8aa9-9acd0148be8c`,
                category: `powerlifting`,
                reviews: 75,
            },
            {
                id: uuidv4(),
                workoutProgramTitle: `Calgary Barbell Programs`,
                workoutProgramDesc: `Written by Calgary Barbell, the 16 week and 8 week programs are designed to improve the squat, bench press, and deadlift of the athlete in preparation for a powerlifting meet. You can, however, run them even if you’re not prepping for a meet. Both programs are quite similar, with the primary difference between the two being that the 16 week program has a more full progression of each lift, whereas the 8 week program is more a training snapshot.`,
                equipment: `gym Required`,
                difficulty: `intermediate`,
                workoutSchedule: `any`,
                workoutLength: `any`,
                rating: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                CategoryId: `10dc1790-c24d-4421-8aa9-9acd0148be8c`,
                category: `powerlifting`,
                reviews: 115,
            },
            {
                id: uuidv4(),
                workoutProgramTitle: `Jonnie Candito 6 Week`,
                workoutProgramDesc: `Jonnie Candito’s 6 week program is a powerlifting peaking program. It consists of several short training blocks dedicated to muscular conditioning, hypertrophy, strength, linear weight increases, acclimation to heavy weights, intensity, and testing. It is held in especially high regard for improving the one rep max of the squat, though it programs all three lifts.`,
                equipment: `gym Required`,
                difficulty: `intermediate`,
                workoutSchedule: `5-7 Days/Week`,
                workoutLength: `1-2 Hours`,
                rating: 5,
                createdAt: new Date(),
                updatedAt: new Date(),
                CategoryId: `10dc1790-c24d-4421-8aa9-9acd0148be8c`,
                category: `powerlifting`,
                reviews: 125,
            },
            {
                id: uuidv4(),
                workoutProgramTitle: `Greg Nuckols 28 Programs`,
                workoutProgramDesc: `Every program runs on a 4 week cycle, with the lifter testing their 1RM after each cycle. Intermediate and advanced cycles start bringing in variations of the main lift (e.g. programming in a front squat as a variation to the back squat), while the beginner programs stick more closely to the big three lifts in the interest of specificity and learning the movement.`,
                equipment: `gym Required`,
                difficulty: `any`,
                workoutSchedule: `any`,
                workoutLength: `any`,
                rating: 5,
                createdAt: new Date(),
                updatedAt: new Date(),
                CategoryId: `10dc1790-c24d-4421-8aa9-9acd0148be8c`,
                category: `powerlifting`,
                reviews: 45,
            },
        ]);
    },

    down: async (queryInterface, Sequelize) => {
        const Op = Sequelize.Op;
        await queryInterface.bulkDelete('workoutPrograms', {
            [Op.or]: [
                { workoutProgramTitle: `Jim Wendler's 5/3/1` },
                { workoutProgramTitle: `StrongLifts 5x5` },
                { workoutProgramTitle: `Chinese Olympic Weightlifting Program` },
                { workoutProgramTitle: `Murph CrossFit Program` },
                { workoutProgramTitle: `German Volume Training` },
            ],
        });
        /**
         * Add commands to revert seed here.
         *
         * Example:
         * await queryInterface.bulkDelete('People', null, {});
         */
    },
};
